"""Pydantic schemas package."""

from app.schemas.article import (
    Article,
    ArticleCreate,
    ArticleInDB,
    ArticleList,
    ArticlePublish,
    ArticleUpdate,
)
from app.schemas.category import (
    Category,
    CategoryBreadcrumb,
    CategoryBulkUpdate,
    CategoryCreate,
    CategoryMove,
    CategorySearchResult,
    CategoryStats,
    CategoryTree,
    CategoryUpdate,
)
from app.schemas.file import (
    File,
    FileBulkUploadResponse,
    FileCreate,
    FileSearchResult,
    FileStats,
    FileUpdate,
    FileUploadResponse,
)
from app.schemas.paper import (
    Paper,
    PaperCreate,
    PaperInDB,
    PaperList,
    PaperRating,
    PaperStatus,
    PaperUpdate,
)
from app.schemas.tag import (
    Tag,
    TagBulkCreate,
    TagCreate,
    TagInDB,
    TagList,
    TagMerge,
    TagUpdate,
    TagUsageStats,
)

__all__ = [
    "Article",
    "ArticleCreate",
    "ArticleUpdate",
    "ArticleInDB",
    "ArticleList",
    "ArticlePublish",
    "Category",
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryBreadcrumb",
    "CategoryBulkUpdate",
    "CategoryMove",
    "CategorySearchResult",
    "CategoryStats",
    "CategoryTree",
    "File",
    "FileCreate",
    "FileUpdate",
    "FileUploadResponse",
    "FileBulkUploadResponse",
    "FileSearchResult",
    "FileStats",
    "Paper",
    "PaperCreate",
    "PaperUpdate",
    "PaperInDB",
    "PaperList",
    "PaperRating",
    "PaperStatus",
    "Tag",
    "TagCreate",
    "TagUpdate",
    "TagInDB",
    "TagList",
    "TagBulkCreate",
    "TagMerge",
    "TagUsageStats",
]
